version: '3.8'
services:
  chatify-frontend: 
    build: 
      context: ./client
      dockerfile: devDockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  chatify-backend:
    build: 
      context: ./server
      dockerfile: devDockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT={PORT}
    
    volumes:
      - ./server:/server

