version: '3.8'
services:
  chatify-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"

  chatify-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
